### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by tanz-tilsontech** [fulcrumapp/fulcrum-styler#38]
When accessing this page it doesn't show anything like the picture and when saving the Embed link it doesn't pull up the map nor any Fulcrum Data.

![image](https://user-images.githubusercontent.com/36584403/36348847-b7bf29c2-1435-11e8-898f-1bdcfbfa4dbe.png)

**Comment by geosamuelsf** [comment]
I have the same problem...

**Comment by bmcbride** [comment]
This project is no longer active and will be removed.
